export enum AppErrorCode {
    INVALID_CREDENTIALS = 'API-101',
    EMAIL_ALREADY_EXISTS = 'API-102',
    USER_NOT_FOUND = 'API-103',
    INVALID_USER_TYPE = 'API-104',
    INVALID_EMAIL = 'API-105',
    INVALID_NAME = 'API-106',
    INVALID_PASSWORD = 'API-107',
    INVALID_INPUT = 'API-051',
    INTERNAL_ERROR = 'API-052',
}